export const CATALOG = Object.freeze({
  "weekend-camera": {
    id: "weekend-camera",
    journey: "weekend",
    merchantId: "weekend-camera-shop",
    merchant: "Weekend Camera Shop (synthetic)",
    currency: "USD",
    amountMinor: 5999,
    quoteVersion: "weekend-1",
    items: [{ id: "camera-kit", name: "旅行相机套装", quantity: 1, unitAmountMinor: 5999 }],
  },
  "weekend-coffee": {
    id: "weekend-coffee",
    journey: "weekend",
    merchantId: "harbor-coffee",
    merchant: "Harbor Coffee (synthetic)",
    currency: "USD",
    amountMinor: 1899,
    quoteVersion: "weekend-1",
    items: [{ id: "coffee-beans", name: "周末咖啡豆", quantity: 1, unitAmountMinor: 1899 }],
  },
  "weekend-headphones": {
    id: "weekend-headphones",
    journey: "weekend",
    merchantId: "sound-garden",
    merchant: "Sound Garden (synthetic)",
    currency: "USD",
    amountMinor: 7999,
    quoteVersion: "weekend-1",
    items: [{ id: "headphones", name: "降噪耳机", quantity: 1, unitAmountMinor: 7999 }],
  },
  "travel-hotel": {
    id: "travel-hotel",
    journey: "travel",
    merchantId: "harbor-hotel",
    merchant: "Harbor Hotel (synthetic)",
    currency: "HKD",
    amountMinor: 8800,
    quoteVersion: "travel-2",
    items: [{ id: "hotel-night", name: "海滨酒店一晚", quantity: 1, unitAmountMinor: 8800 }],
  },
  "travel-transit": {
    id: "travel-transit",
    journey: "travel",
    merchantId: "city-transit",
    merchant: "City Transit (synthetic)",
    currency: "HKD",
    amountMinor: 2600,
    quoteVersion: "travel-2",
    items: [{ id: "transit-pass", name: "城市交通通票", quantity: 1, unitAmountMinor: 2600 }],
  },
  "travel-guide": {
    id: "travel-guide",
    journey: "travel",
    merchantId: "open-guide-api",
    merchant: "Open Guide API (synthetic)",
    currency: "USDC",
    amountMinor: 1200000,
    quoteVersion: "travel-2",
    items: [{ id: "neighborhood-guide", name: "街区实时指南（按次）", quantity: 1, unitAmountMinor: 1200000 }],
  },
});

export const CURRENCIES = Object.freeze({
  USD: { decimals: 2, initialMinor: 30000 },
  HKD: { decimals: 2, initialMinor: 15000 },
  USDC: { decimals: 6, initialMinor: 5000000 },
});
